#' p_value
#'
#' This function calculates p-values for observed vs expected allele frequencies
#' @param df A data frame generated by the adsim() function
#' @param observed_freq Observed allele frequency
#' @return a data frame showing observed allele frequencies, expected allele
#'   frequencies, z-scores, and p-values for each combination of p1, p2, and admixture
#'   proportion
#' @export
#' @examples
#' test <- adsim(ngens = 10, k = 2, l = 5, admix = c(0.2, 0.5),
#' m1 = 0.01, m2 = 0.01, ne = 100, p1 = 0.5,
#' p2 = 0.9, nsims = 10)
#'
#' obs_freq <- 0.9
#'
#' p_values(test, obs_freq)

p_values <- function(df, observed_freq){

  standard <- sim_overview(df) %>%
    dplyr::mutate(obs_freq = observed_freq)

  standard <- standard %>%
    dplyr::group_by(.data$p1, .data$p2, .data$admix)%>%
    dplyr::transmute(
      #obs_freq = .data$mean_pF,
      exp_freq = (.data$admix * .data$p1) + ((1-.data$admix)* .data$p2),
      z = (.data$obs_freq - .data$exp_freq)/.data$sd_pF,
      p = 2*(1-stats::pnorm(abs(z)))
    )
  return(standard)
}
