#' z_value
#'
#' This function calculate z-scores for observed vs expected allele frequencies
#' @param df A data frame generated by the adsim() function
#' @return a data frame showing observed allele frequencies, expected allele
#'   frequencies, and z-scores for each combination of p1, p2, and admixture
#'   proportion
#' @export
#' @examples
#' test <- adsim(ngens = 10, k = 2, l = 5, admix = c(0.2, 0.5),
#' m1 = 0.01, m2 = 0.01, ne = 100, p1 = 0.5,
#' p2 = 0.9, nsims = 10)
#' z_value(test)
z_value <- function(df){
  standard_score <- sim_overview(df) %>%
    dplyr::group_by(.data$p1, .data$p2, .data$admix) %>%
    dplyr::transmute(
      # sd_pF = sd_pF,
      # p1 = p1,
      # p2 = p2,
      obs_freq = .data$mean_pF,
      #.data explicitly asks R to look for the variable in the current data frame
      exp_freq = (.data$admix * .data$p1) + ((1-.data$admix)* .data$p2),
      z = (.data$obs_freq - .data$exp_freq)/.data$sd_pF
    )
  return(standard_score)
  }



